services:
  db:
    image: postgres:18
    container_name: berka_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: berka
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/data

volumes:
  pgdata: